services:
  gin:
    container_name: gin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8100:8100
    environment:
      PORT: ${GIN_PORT}
      POSTGRES_NAME: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
  db:
    image: postgres
    environment:
      POSTGRES_NAME: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres/:/var/lib/postgresql/data
